version: "3"
services:
  backend:
    container_name: backend-con
    build: .
    image: backend
    environment:
      - MYSQL_DATABASE=maskawa
      - MYSQL_USER=backend
      - MYSQL_ROOT_PASSWORD=int222backend
    volumes:
      - /home/Maskawa/Back-End/public:/tmp
    networks:
      intregrated-network:
        ipv4_address: 172.18.0.1
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: intregrated-network
  intregrated-network:
    external: true
